hemorrhage_decoder:
  decoder_channels: [512, 256, 128, 64, 32]
  normalization: instance
  activation: relu
  dropout: 0.2

keypoint_decoder:
  decoder_channels: [256, 128, 64, 32, 16]
  normalization: instance
  activation: relu
  dropout: 0.2

detection:
  fpn_channels: 256
  atss_candidates: 4

  hard_negative:
    batch_size: 256
    positive_fraction: 0.25
    minimum_negative: 16
    pool_size: 20.0

  inference:
    score_threshold: 0.05
    nms_threshold: 0.4
    max_detections: 25

  anchor_boxes:
    shapes:
      - [42, 22]
      - [38, 26]
      - [32, 32]
      - [26, 38]
      - [22, 42]
